  app:
    image: devopsintita/intita:php5-dev-latest
    user: ${USER_ID}:${USER_GID}
    container_name: "IntITA_app"
    working_dir: /app
    hostname: app
    volumes:
      - ./:/appcd
      - ./docker_conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db
      - redis
    environment:
      XDEBUG_CONFIG: ${XDEBUG_CONFIG}

  nginx:
    container_name: "IntITA_nginx"
    image: nginx:1.12-alpine
    ports:
      - ${NGINX_IP}:${NGINX_HTTP_PORT}:80
    volumes:
      - ./:/app
      - ./docker_conf/nginx/intita.conf:/etc/nginx/conf.d/vhost.conf
    links:
      - app

  mailcatcher:
      container_name: "IntITA_mailcatcher"
      image: schickling/mailcatcher:latest
      ports:
        - 1080:1080

  db:
    image: mysql:5.7
    user: ${USER_ID}:${USER_GID}
    container_name: "IntITA_db"
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
      - ./docker_conf/mysql:/etc/mysql
    ports:
      - ${MYSQL_LOCAL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWD}
  redis:
    image: redis:latest
